# Site
repository: lavumi/resmue-page
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 김도영
title: Senior Developer
email: me@lavumi.net
website: https://lavumi.net/

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  lavumi
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: lavumi
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Fun Projects
  icon: fa-solid fa-house-chimney
  url: https://lavumi.net/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  게임 클라이언트 개발로 시작하여, 렌더링, 실시간 게임 서버, 웹서버 등 다양한 분야들을 시도해보고 있는 호기심 많은 개발자입니다.
  주된 업무로 서버 개발을 하고 있으며, 이전 회사에서는 사내 서버의 테섭, Redmine, Wiki, Homepage 등을 구축,운영등의 업무도 맡고 있습니다.
  최근에는 <mark>Go</mark> 와 <mark>Rust</mark>에 매력을 느껴 두 언어에 대한 다양한 프로젝트를 진행해보며 공부중입니다.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Labconnect
        sub_title: Senior Developer
        caption: 2024.04 - Present
#        link: github.com/sproogen
        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          - Hospital-Medical Device Integration System Development 
          - Full-Stack Development
      - layout: left
        title: 슬롯 머신 게임
        sub_title: 프로젝트 매니저 및 서버 개발자
        caption: 2022.09 ~ 2023.11
        description: | # this will include new lines to allow paragraphs
          - 슬롯 게임 서버 개발 (C# ASP.NET)
          - 파시트 설계 및 가이드
          - 환수율 검증기 (C#)
          - 타사 슬롯 분석 프로그램 (Go)
          - 환수율 모니터링 시스템 (Node.js Express)
      - layout: left
        title: 코인 플랫폼 유지보수
        caption: 2022.02 ~ 2022.08
        description: | # this will include new lines to allow paragraphs
          - 기존 시스템 개선 및 신규 컨텐츠 ( Java Spring Boot ) 
          - CS 이슈 처리 및 지갑 관리, 이더리움 노드( Geth ) 운영 
          - 노드 모니터링, 알림 시스템 개발
      - layout: left
        title: FudaLotto
        link: https://play.google.com/store/apps/details?id=tw.com.fudalotto
        link_text: Project Link
        caption: 2022.02 ~ 2022.08
        description: | # this will include new lines to allow paragraphs
          - 대만 복권 예측번호 알림 앱 개발 
          - 서버 개발 전반과 클라이언트 구조 설계 및 가이드 
          - Aws 에서 nCloud 로 서비스 이전
      - layout: left
        title: No Pickles - pet escape
        caption: 2022.02 ~ 2022.08
        link: https://www.facebook.com/NoPicklesGame/
        link_text: Project Link
        quote: >
          가장 재밌었던 프로젝트입니다. 그만큼 아쉬움과 후회도 많구요.
        description: | # this will include new lines to allow paragraphs
          사내 소규모 프로젝트로 어몽어스 류의 게임 제작, Facebook Instant Game에 출시
          클라이언트( Cocos Creator )와 서버 (Node.js) 개발
      - layout: left
        title: Rock'N Cash
        caption: 2018.08 ~ 2020.11
        description: | # this will include new lines to allow paragraphs
          소셜 카지노 게임 유지보수
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Zipida
        sub_title: Software engineer
        caption: 2024.04 ~ Present
      - layout: top-middle
        title: CandiCode
        sub_title: Backend developer
        caption: 2022.09 ~ 2023.11
      - layout: top-middle
        title: VanillaCode
        sub_title: Backend developer
        caption: 2022.01 ~ 2022.08
      - layout: top-middle
        title: Flysher
        sub_title: Game client developer
        caption: 2018.08 ~ 2021.11
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 학점은행제
        caption: 2017.08 ~ 2018.02
        sub_title: 컴퓨터과학
      - layout: top-middle
        title: 한양대학교
        caption: 2005.03 ~ 2013.02
        sub_title: 의학과 (중퇴)

  - title: My Fun Projects
    layout: text
    content: | # this will include new lines to allow paragraphs
      Plz visit my [Homepage](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
